version: '3.5'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
  
  clickhouse01:
    image: clickhouse/clickhouse-server:22.5
    container_name: clickhouse01
    hostname: clickhouse01
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper
  
  clickhouse02:
    image: clickhouse/clickhouse-server:22.5
    container_name: clickhouse02
    hostname: clickhouse02
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper
  
  clickhouse03:
    image: clickhouse/clickhouse-server:22.5
    container_name: clickhouse03
    hostname: clickhouse03
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zookeeper
  
  clickhouse04:
    image: clickhouse/clickhouse-server:22.5
    container_name: clickhouse04
    hostname: clickhouse04
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
    depends_on:
      - zookeeper
